### PR TITLE
Updated is_safe_url to match current django trunk.

### PR DESCRIPTION
**Pull request by apollo13**

### CODE REVIEW

**Comment by apollo13** [comment]
Do you think it would be possible to move this repo under the django umbrella and update oss-fuzz to use that then?

**Comment by guidovranken** [comment]
Thanks!

> Do you think it would be possible to move this repo under the django umbrella and update oss-fuzz to use that then?

Sure! How do you suggest we do this? You can create a repo in `django` and copy the files over and give me write access. I'm not sure how to transfer the repo directly or if it's even possible.

**Comment by apollo13** [comment]
If you visit the repository settings you should see a section "danger zone". There you should be able to select `django` as the new owner. I'll see that I can confirm the transfer on our end.

**Comment by guidovranken** [comment]
I get

```
You don’t have the permission to create public repositories on django 
```

**Comment by guidovranken** [comment]
Maybe you can do it, you should have access to this repo.

**Comment by apollo13** [comment]
Mhm, no access to the repository settings; I'll just clone and push it to django then :/

**Comment by apollo13** [comment]
I have added you to the new repo. Do I need to make a PR against https://github.com/google/oss-fuzz/blob/master/projects/django/Dockerfile#L20 next?

**Comment by guidovranken** [comment]
> I have added you to the new repo. Do I need to make a PR against https://github.com/google/oss-fuzz/blob/master/projects/django/Dockerfile#L20 next?

Thanks. Correct, that should do it.

**Comment by guidovranken** [comment]
PS @apollo13 I'd be interested in extending the current fuzzer a bit if you have any ideas as to which functions to test. Feel free to e-mail me to discuss this.

**Comment by apollo13** [comment]
That sounds great, I'll think a bit about it. Have to refresh on what already exists.

**Pull request merged**
